# Generated by Django 5.2.5 on 2025-08-28 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('slot', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('monday', models.CharField(blank=True, max_length=20, null=True)),
                ('tuesday', models.CharField(blank=True, max_length=20, null=True)),
                ('wednesday', models.CharField(blank=True, max_length=20, null=True)),
                ('thursday', models.CharField(blank=True, max_length=20, null=True)),
                ('friday', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timetable',
            },
        ),
    ]
