# Generated by Django 5.2.5 on 2025-08-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_academiccalendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccalendar',
            name='id',
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='acdid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
