# Generated by Django 5.2.5 on 2025-09-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_timetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiccalendar',
            name='acdid',
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
