# Generated by Django 5.2.5 on 2025-10-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_academiccalendar_acdid_academiccalendar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='hours_attended',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_hours',
            field=models.IntegerField(null=True),
        ),
    ]
