# Generated by Django 5.2.5 on 2025-10-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_subject_hours_attended_subject_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='attendance',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
