# Generated by Django 5.2.5 on 2025-10-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_subject_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjectName',
            field=models.CharField(max_length=30),
        ),
    ]
